/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stddef.h>
#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Timer2_init(void) {
	RCC->APB1ENR |= (1U << 0);

	TIM2->PSC = 16000 - 1;
	TIM2->ARR = 2000 - 1;
	TIM2->CNT = 0;

	TIM2->DIER |= TIM_DIER_UIE; /*after overflow, raise the interrupt to its channel*/

	NVIC_EnableIRQ(TIM2_IRQn); /*Enable the TIM2_IRQn slot.*/

	TIM2->CR1 = (1U<<0);
}


void TIM2_IRQHandler(void) {
	TIM2->SR &= ~(1U<<0);
	puts("I'm in TIM2_ISR");
	GPIOA->ODR ^=(1 << 5);
//	for(uint32_t i = 0; i < 50000U; i++);
}


void GPIO_Init(void) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; /**/
	GPIOA->MODER |= (1 << 10);
	GPIOA->OTYPER &= ~(1 << 5);
	GPIOA->OSPEEDR |= (1 << 10);
	GPIOA->PUPDR &= ~(3 << 10);
}

int main(void)
{
	GPIO_Init();
	Timer2_init();
	puts("I'm in main");
    /* Loop forever */
	for(;;) {
		puts("I'm in while");
		for(uint32_t i = 0; i < 5000000U; i++);
	}
}
