/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Timer2_Init(uint32_t delay) {
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->PSC = 160000 - 1;
	TIM2->ARR = (100  - 1) * delay;
	TIM2->CNT = 0;

	TIM2->DIER |= TIM_DIER_UIE;

	NVIC_EnableIRQ(TIM2_IRQn);
}

void TIM2_IRQHandler(void) {
	TIM2->SR &= ~TIM_SR_UIF;
	printf("Tim2_IRQHandler\n");
	GPIOA->ODR ^= (1U << 0);
}

void start_Timer2() {
	TIM2->CR1 |= TIM_CR1_CEN;
}

void GPIOA_Init(uint32_t pin) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	GPIOA->MODER |= (1U << (2 * pin));
	GPIOA->OTYPER &= ~(1U << pin);
	GPIOA->OSPEEDR |= (3U << (2 * pin));
	GPIOA->PUPDR |= (1U << (2 * pin));
}

int main(void)
{
	GPIOA_Init(0u);
	Timer2_Init(1U);

	start_Timer2();
    /* Loop forever */
	for(;;) {
		printf("main-for\n");
	}
}
