/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stddef.h>
#include "stm32f446xx.h"
#include "gpiox_config.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	char GPIOx1 = 'A', GPIOx2 = 'C';
	uint8_t pin_number1 = 0U, pin_number2 = 13U;

	GPIOx_init(GPIOx1, pin_number1, OUTPUT);
	GPIOx_init(GPIOx2, pin_number2, INPUT);

    /* Loop forever */
	for(;;) {
//		if (is_IDR_ON_at_pin(GPIOx2, pin_number2)) {
//			set_ODR_at_pin(GPIOx1, pin_number1);
//		} else {
//			reset_ODR_at_pin(GPIOx1, pin_number1);
//		}

		if (is_IDR_ON_at_pin(GPIOx2, pin_number2)) {
			if (is_pin_set(GPIOx1, pin_number1)) {
				reset_ODR_at_pin(GPIOx1, pin_number1);
			} else {
				set_ODR_at_pin(GPIOx1, pin_number1);
			}
		}
	}

	return 0;
}
