/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/*
 * Question: while pressed, LED should blink faster, else slower
 * */


#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define __IO volatile

#define RCC_BASE 				(0x40023800)
#define RCC_OFFSET				(RCC_BASE + 0x30)
#define RCC						((__IO uint32_t *) RCC_OFFSET)

typedef struct
{
  __IO uint32_t MODER;    /*!< GPIO port mode register,               Address offset: 0x00      */
  __IO uint32_t OTYPER;   /*!< GPIO port output type register,        Address offset: 0x04      */
  __IO uint32_t OSPEEDR;  /*!< GPIO port output speed register,       Address offset: 0x08      */
  __IO uint32_t PUPDR;    /*!< GPIO port pull-up/pull-down register,  Address offset: 0x0C      */
  __IO uint32_t IDR;      /*!< GPIO port input data register,         Address offset: 0x10      */
  __IO uint32_t ODR;      /*!< GPIO port output data register,        Address offset: 0x14      */
  __IO uint32_t BSRR;     /*!< GPIO port bit set/reset register,      Address offset: 0x18      */
  __IO uint32_t LCKR;     /*!< GPIO port configuration lock register, Address offset: 0x1C      */
  __IO uint32_t AFR[2];   /*!< GPIO alternate function registers,     Address offset: 0x20-0x24 */
} GPIO_TypeDef;

#define GPIOA_BASE				(0x40020000)
#define GPIOC_BASE				(0x40020800)
#define GPIOA					((__IO GPIO_TypeDef *) GPIOA_BASE)
#define GPIOC					((__IO GPIO_TypeDef *) GPIOC_BASE)

void GPIOA_Init(uint32_t pin) {
	*RCC |= (1U << 0);

	GPIOA->MODER |= (1U << (2 * pin));
	GPIOA->OTYPER &= ~(1U << pin);
	GPIOA->OSPEEDR |= (1U << (2 * pin));
	GPIOA->PUPDR |= (2U << (2 * pin));
}

void GPIOC_Init(uint32_t pin) {
	*RCC |= (1U << 2);

	GPIOC->MODER &= ~(1U << (2 * pin));
	GPIOC->OSPEEDR |= (1U << (2 * pin));
	GPIOC->PUPDR |= (2U << (2 * pin));
}


int main(void)
{
	uint32_t pin1 = 5, pin2 = 13;
	GPIOA_Init(pin1);
	GPIOC_Init(pin2);

	uint32_t delay = 50u;
    /* Loop forever */
	for(;;) {
		GPIOA->ODR |= (1U << pin1);
		for (uint32_t i = 0u; i < (50000 * delay); i++) {
			if (!(GPIOC->IDR & (1U << pin2))) {
				delay = 1u;
			} else {
				delay = 5u;
			}
		}

		delay = 5u;
		GPIOA->ODR &= ~(1U << pin1);
		for (uint32_t i = 0u; i < (50000 * delay); i++) {
			if (!(GPIOC->IDR & (1U << pin2))) {
				delay = 1u;
			} else {
				delay = 5u;
			}
		}
	}
	return 0;
}



