/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "gpiox_config.h"
#include "timer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	char GPIOx = 'A';
	uint32_t pin0= 0u;

	Timer2_Init(10u);
//	Timer5_Init(40u);

	GPIOx_init(GPIOx, pin0, OUTPUT);
//	GPIOx_init(GPIOx, pin1, OUTPUT);

//	set_ODR_at_pin(GPIOx, pin0);
//	set_ODR_at_pin(GPIOx, pin1);

	start_Timer2();
//	start_Timer5();
    /* Loop forever */
	for(;;);
}
