/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif





int main(void)
{
	float val = 1.4;
	uint32_t dac_value = 0x0;
	uint32_t i = 0;

	// enable GPIOA clock, bit 0 on AHB1ENR
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // (1 << 0);

	GPIOA->MODER &= ~(3 << 8); // Reset bits 8-9 to clear old values. Its considered a good practice
	GPIOA->MODER |= (3 << 8); // Set pin

	// enable DAC clock, bit 29 on APB1ENR
	RCC->APB1ENR |= RCC_APB1ENR_DACEN; // (1 << 29);

	DAC->CR |= DAC_CR_EN1; // (1 << 0); 	// enable DAC for channel 1
	DAC->CR &= ~DAC_CR_BOFF1; // ~(1 << 1);	// enable DAC channel 1 O/P buffer
	DAC->CR |= DAC_CR_TEN1; // (1 << 2);	// enable trigger
	DAC->CR |= DAC_CR_TSEL1; // (7 << 3);	// choose software trigger as source(0b111)

	// set output to Vref* (dac_value/0XFFF)
	DAC->DHR12R1 = dac_value;
//	DAC->SWTRIGR |= DAC_SWTRIGR_SWTRIG1; // (1 << 0)	// Trigger Channel 1
	DAC->SWTRIGR |= (1 << 0); // (1 << 0)	// Trigger Channel 1

	uint8_t go_up = 1u;
    /* Loop forever */
	for(;;) {
		dac_value = (val * 4095) / 3.3f;
		DAC->DHR12R1 = dac_value;
//		DAC->SWTRIGR |= DAC_SWTRIGR_SWTRIG1;
		DAC->SWTRIGR |= (1 << 0); // Trigger Channel 1

//		printf("dac: %ld, val: %f, go_up: %u\n", dac_value, val, go_up);
		for(i = 0; i < 50000; i++);
		if (val >= 2.2) go_up = 0u;
		else if (val <= 1.4) go_up = 1u;


		if (go_up) {
			val += 0.01;
		} else {
			val -= 0.01;
		}

	}

	return 0;
}
