/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f446xx.h"
#include "gpiox_config.h"
#include "timer.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t pin0 = 0u;
//	uint32_t pin1 = 13u;

	char GPIOxA = 'A';
//	char GPIOxC = 'C';
	GPIOx_init(GPIOxA, pin0, OUTPUT);
//	GPIOx_init(GPIOxC, pin1, INPUT);
	Timer2_init_WI();

//	uint8_t flag = 0u;
	uint32_t duty_cycle = 1u;
//	uint8_t interval = 0u;
	uint8_t fade_in = 1u;
    /* Loop forever */
	for(;;) {
		if (fade_in) {
			duty_cycle = (duty_cycle + 1u) % 101u;
			if (duty_cycle >= 100u) {
				fade_in = 0u;
			}

		} else {
			if (duty_cycle <= 10u) {
				duty_cycle = 2u;
				fade_in = 1u;
			}
			duty_cycle = (duty_cycle - 1u) % 101u;
		}

		set_ODR_at_pin(GPIOxA, pin0);
		TIM2_delay(duty_cycle);
		reset_ODR_at_pin(GPIOxA, pin0);
		TIM2_delay(101u - duty_cycle);
	}
}
