/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <math.h>
#include "stm32f446xx.h"
#include "gpiox_config.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Timer2_Init(void) {
	// Enable RCC APB1ENR for TIM
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	TIM2->PSC = (1600 - 1);
	TIM2->ARR = (50 - 1);
	TIM2->CNT = 0;
}

void TIM2_delay(uint32_t delay_time_in_sec) {
	uint32_t ARR_default = TIM2->ARR;
	TIM2->ARR *= delay_time_in_sec;

	// start timer
	// when the CR1 is set, the timer begins
	TIM2->CR1 |= (1U << 0);
	while (!(TIM2->SR & (0X0001)));
	TIM2->SR &= ~(1 << 0);
	TIM2->CR1 &= ~(1U << 0); // not necessary. This happens by default

	TIM2->ARR = ARR_default;
}


int main(void)
{
	char GPIOx = 'A';
	uint32_t pin = 0;
	uint32_t delay = 2000;

	GPIOx_init('A', pin, OUTPUT);
	Timer2_Init();

    /* Loop forever */
	for(uint32_t i = delay; i >= 0; i -=10) {
		set_ODR_at_pin(GPIOx, pin);
		TIM2_delay((uint32_t) log(i));
		reset_ODR_at_pin(GPIOx, pin);
		TIM2_delay((uint32_t) log(i));
	}

	return 0;
}
