/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void Timer2_init(void) {
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->PSC = 16000 - 1;
	TIM2->ARR = 1000 - 1;
	TIM2->CNT = 0;

	TIM2->DIER |= TIM_DIER_UIE;

	NVIC_EnableIRQ(TIM2_IRQn);

	TIM2->CR1 |= TIM_CR1_CEN;
}

void TIM2_IRQHandler(void) {
	TIM2->SR &= ~TIM_SR_UIF;

	// LED at PA0 and PA1
	if (GPIOA->ODR & (1 << 0)) {
		if (GPIOA->ODR & (1 << 1)) {
			GPIOA->ODR &=  ~(1 << 0);
		} else {
			GPIOA->ODR |= (1 << 1);
		}
	} else {
		if (GPIOA->ODR & (1 << 1)) {
			GPIOA->ODR &=  ~(1 << 1);
		} else {
			GPIOA->ODR |= (1 << 0);
		}
	}

	// simple LEDs toggle
//	GPIOA->ODR ^= (1 << 0) | (1 << 1);
}

void GPIOA_init(uint32_t pin_number) {
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER |= (1 << (2 * pin_number));
	GPIOA->OTYPER &= ~(1 << pin_number);
	GPIOA->OSPEEDR |= (3 << (2 * pin_number));
	GPIOA->PUPDR &= ~(3 << (2 * pin_number));
}

void GPIOA_set_LEDs(uint32_t pin_number1, uint32_t pin_number2, uint32_t relation) {
	// 0: same
	// 1: opposite
	switch(relation) {
		case 0:
			GPIOA->ODR |= (1 << pin_number1);
			GPIOA->ODR |= (1 << pin_number2);
			break;
		case 1:
			GPIOA->ODR |= (1 << pin_number1);
			GPIOA->ODR &= ~(1 << pin_number2);
			break;
	}
}

int main(void)
{
	GPIOA_init(0);
	GPIOA_init(1);
	Timer2_init();

	// make sure both LEDs are on opposite
	// states to begin with
	GPIOA_set_LEDs(0, 1, 1);

    /* Loop forever */
	for(;;);
}
