/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "gpiox_config.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void Timer2_init(void) {
	// Enable RCC APB1ENR for TIM
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	TIM2->PSC = (16000 - 1);
	TIM2->ARR = (1000 - 1);
	TIM2->CNT = 0;

}

void Timer2_delay(const uint32_t delay) {
	uint32_t ARR_default = TIM2->ARR;
	TIM2->ARR *= delay;

	// start timer
	// when the CR1 is set, the timer begins
	TIM2->CR1 |= (1U << 0);
	while (!(TIM2->SR & (0X0001)));
	TIM2->SR &= ~(1 << 0);
	TIM2->CR1 &= ~(1U << 0); // not necessary. This happens by default

	TIM2->ARR = ARR_default;
}


int main(void)
{
	char GPIOx = 'A';
	uint8_t pin1 = 0, pin2 = 1;

	GPIOx_init(GPIOx, pin1, OUTPUT);
	GPIOx_init(GPIOx, pin2, OUTPUT);
	Timer2_init();


	uint32_t delay = 1U;

    /* Loop forever */
	for(;;) {
		// pattern 1
		set_ODR_at_pin(GPIOx, pin1);
		reset_ODR_at_pin(GPIOx, pin2);
		Timer2_delay(delay);

		// pattern 2
		set_ODR_at_pin(GPIOx, pin1);
		set_ODR_at_pin(GPIOx, pin2);
		Timer2_delay(delay);

		// pattern 3
		reset_ODR_at_pin(GPIOx, pin1);
		set_ODR_at_pin(GPIOx, pin2);
		Timer2_delay(delay);

		// pattern 4
		reset_ODR_at_pin(GPIOx, pin1);
		reset_ODR_at_pin(GPIOx, pin2);
		Timer2_delay(delay);
	}
}
